### ISSUE TITLE
Wrong duration for large videos

### ISSUE THREAD

**Issue by cechus** [mamanipatricia/youtube-clone#38]
Wrong duration for large videos
can you check this example:
![image](https://user-images.githubusercontent.com/11302363/178537255-6c9ae3ed-5c34-4508-ad0d-70e3433caff5.png)

Original
![image](https://user-images.githubusercontent.com/11302363/178536219-64ce0fe0-cd24-42e7-b583-f87eac46b4da.png)
[https://www.youtube.com/results?search_query=lofi+hip+hop+radio+-+beats+to+relax%2Fstudy+to](https://www.youtube.com/results?search_query=lofi+hip+hop+radio+-+beats+to+relax%2Fstudy+to)

**Comment by mamanipatricia** [comment]
I cannot reproduce the issue
